version: '3.1'
services:
  mysql:
    image: mysql
    command: ['mysqld','--character-set-server=utf8']
    ports:
      - 9002:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  openemr_local_development:
    image: openemr_local_development
    ports:
      - 9001:80
    volumes:
      - ./openemr:/var/www/localhost/htdocs/openemr
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASS: root
      MYSQL_USER: root
      MYSQL_PASS: root
      OE_USER: admin
      OE_PASS: pass
    links:
      - mysql
