# Use admin/pass as user/password credentials
version: '3.1'
services:
  mysql:
    restart: always
    image: mysql
    command: ['mysqld','--character-set-server=utf8']
    environment:
      MYSQL_ROOT_PASSWORD: root
  openemr:
    restart: always
    image: openemr_local_development
    ports:
    - 8000:80
    - 8001:443
    volumes:
    - logvolume01:/var/log
    - ./openemr:/var/www/localhost/htdocs/openemr
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASS: root
      MYSQL_USER: root
      MYSQL_PASS: root
      OE_USER: admin
      OE_PASS: pass
    links:
    - mysql
volumes:
  logvolume01: {}
  sitevolume: {}
